[package]
name = "manifold"
version.workspace = true
edition.workspace = true

[dependencies]
app = { path = "../app" }
clap = { version = "4", features = ["derive"] }
input = { path = "../input" }
platform = { path = "../platform" }
render = { path = "../render" }
ui = { path = "../ui" }
